// Лейбл для сторінки лідів - налаштування видимості

export const labelNamesLids = {
  name: "Ім'я",
  phone: "Телефон",
};

export const statusLidsMapping ={
  new: "Новий",
  contact: "Контакт",
  payment: "Оплата",
  appointments: "Обладнання",
  connection: "Підключення",
};

// Тимчасовий масив для сторінкі Лідів

export const cardsLids = [
  {
    id: 1,
    photo_url: null,
    name: "Віталій Голобородько",
    phone: "0663123466",
    company: "Мастер Сервіс",
    status: "new",
    date: null,
    time: null,
    event:null,
    post: 23,
    city: "Київ",
  },
  {
    id: 2,
    photo_url: null,
    name: "Віталій Голобородько",
    phone: "0663155466",
    company: "Мастер Сервіс",
    status: "contact",
    date: "2025-01-26",
    time: "15:45",
    event:"Презентація продукту",
    post: 23,
    city: "Київ",
  },
  {
    id: 3,
    photo_url: null,
    name: "Іван Кондратекно",
    phone: "0507953489",
    company: "Спектр",
    status: "appointments",
    date: "2025-01-08",
    time: "17:00",
    event:"Підключення камер",
    post: 20,
    city: "Чернівці",
  },
  {
    id: 4,
    photo_url: null,
    name: "Іван Кондратекно",
    phone: "0687953555",
    company: "Спектр",
    status: "connection",
    date: "2025-02-01",
    time: "9:00",
    event:"Чек-лист готовності",
    post: 20,
    city: "Чернівці",
  },
  {
    id: 5,
    photo_url: null,
    name: "Олег Кушнір",
    phone: "0637814792",
    company: "Астрал",
    status: "payment",
    date: "2025-01-12",
    time: "18:00",
    event:"Спала за продукт",
    post: 21,
    city: "Харків",
  },
  {
    id: 6,
    photo_url: null,
    name: "Віталій Голобородько",
    phone: "0687953489",
    company: "Мастер Сервіс",
    status: "connection",
    date: "2025-01-15",
    time: "13:00",
    event:"Інтеграція БД клієнта",
    post: 23,
    city: "Київ",
  },
  {
    id: 7,
    photo_url: null,
    name: "Олег Кушнір",
    phone: "0677222792",
    company: "Астрал",
    status: "connection",
    date: "2025-02-01",
    time: "15:30",
    event:"Спала за продукт",
    post: 21,
    city: "Харків",
  },
  {
    id: 8,
    photo_url: null,
    name: "Віталій Голобородько",
    phone: "0687953444",
    company: "Мастер Сервіс",
    status: "connection",
    date: "2025-01-19",
    time: "11:00",
    event:"Створення тестової БД",
    post: 23,
    city: "Київ",
  },
  {
    id: 9,
    photo_url: null,
    name: "Олександр Трухля",
    phone: "0737953111",
    company: "Спектр",
    status: "connection",
    date: "2025-01-08",
    time: "17:00",
    event:"Навчання співробітників",
    post: 15,
    city: "Одеса",
  },
]